// Eight Trigram (팔괘) system data for Korean martial arts

import type { TrigramStance, TrigramData, KoreanTechnique } from "../index";
import { KOREAN_COLORS } from "./colors";

// Trigram techniques data
export const TRIGRAM_TECHNIQUES: Record<TrigramStance, KoreanTechnique> = {
  geon: {
    id: "geon_thunder_strike",
    name: "Thunder Strike",
    koreanName: "천둥벽력",
    englishName: "Heavenly Thunder Strike",
    romanized: "Cheondeung Byeokryeok",
    description: {
      korean: "하늘의 힘으로 직접적인 골격 타격",
      english: "Direct bone-striking force from heavenly power",
    },
    stance: "geon",
    type: "bone_strike",
    damageType: "blunt",
    damageRange: { min: 25, max: 35, type: "blunt" },
    kiCost: 15,
    staminaCost: 20,
    executionTime: 300,
    recoveryTime: 500,
    accuracy: 0.85,
    range: 1.2,
    critChance: 0.15,
    critMultiplier: 1.8,
  },
  tae: {
    id: "tae_flowing_joint",
    name: "Flowing Joint",
    koreanName: "유수연타",
    englishName: "Flowing Lake Strikes",
    romanized: "Yusu Yeontta",
    description: {
      korean: "호수처럼 유동적인 관절 조작",
      english: "Fluid joint manipulation like a peaceful lake",
    },
    stance: "tae",
    type: "joint_lock",
    damageType: "joint",
    damageRange: { min: 18, max: 28, type: "joint" },
    kiCost: 12,
    staminaCost: 15,
    executionTime: 400,
    recoveryTime: 600,
    accuracy: 0.9,
    range: 1.0,
    critChance: 0.12,
    critMultiplier: 1.6,
  },
  li: {
    id: "li_fire_nerve",
    name: "Fire Nerve",
    koreanName: "화염지창",
    englishName: "Flame Finger Strike",
    romanized: "Hwayeom Jichang",
    description: {
      korean: "불꽃같은 정밀한 신경 타격",
      english: "Precise nerve strikes like dancing flames",
    },
    stance: "li",
    type: "nerve_strike",
    damageType: "nerve",
    damageRange: { min: 20, max: 30, type: "nerve" },
    kiCost: 18,
    staminaCost: 12,
    executionTime: 250,
    recoveryTime: 400,
    accuracy: 0.92,
    range: 0.8,
    critChance: 0.2,
    critMultiplier: 2.0,
  },
  jin: {
    id: "jin_thunder_stun",
    name: "Thunder Stun",
    koreanName: "벽력일섬",
    englishName: "Lightning Flash Strike",
    romanized: "Byeokryeok Ilseom",
    description: {
      korean: "천둥같은 기절 기법",
      english: "Stunning techniques like sudden thunder",
    },
    stance: "jin",
    type: "nerve_strike",
    damageType: "nerve",
    damageRange: { min: 22, max: 32, type: "nerve" },
    kiCost: 20,
    staminaCost: 18,
    executionTime: 200,
    recoveryTime: 450,
    accuracy: 0.88,
    range: 1.1,
    critChance: 0.18,
    critMultiplier: 1.9,
  },
  son: {
    id: "son_wind_pressure",
    name: "Wind Pressure",
    koreanName: "선풍연격",
    englishName: "Whirlwind Continuous Strikes",
    romanized: "Seonpung Yeongyeok",
    description: {
      korean: "바람같은 지속적인 압박",
      english: "Continuous pressure like persistent wind",
    },
    stance: "son",
    type: "combo_sequence",
    damageType: "blunt",
    damageRange: { min: 15, max: 25, type: "blunt" },
    kiCost: 10,
    staminaCost: 25,
    executionTime: 500,
    recoveryTime: 300,
    accuracy: 0.82,
    range: 1.3,
    critChance: 0.1,
    critMultiplier: 1.5,
  },
  gam: {
    id: "gam_water_flow",
    name: "Water Flow",
    koreanName: "수류반격",
    englishName: "Water Current Counter",
    romanized: "Suryu Bangyeok",
    description: {
      korean: "물의 흐름처럼 혈류 제한",
      english: "Blood flow restriction like flowing water",
    },
    stance: "gam",
    type: "pressure_point",
    damageType: "blood",
    damageRange: { min: 16, max: 26, type: "pressure" },
    kiCost: 14,
    staminaCost: 16,
    executionTime: 350,
    recoveryTime: 550,
    accuracy: 0.87,
    range: 0.9,
    critChance: 0.14,
    critMultiplier: 1.7,
  },
  gan: {
    id: "gan_mountain_defense",
    name: "Mountain Defense",
    koreanName: "반석방어",
    englishName: "Solid Rock Defense",
    romanized: "Banseok Bangeoh",
    description: {
      korean: "산처럼 견고한 방어적 반격",
      english: "Defensive counters like an immovable mountain",
    },
    stance: "gan",
    type: "counter_attack",
    damageType: "blunt",
    damageRange: { min: 20, max: 30, type: "blunt" },
    kiCost: 16,
    staminaCost: 14,
    executionTime: 400,
    recoveryTime: 500,
    accuracy: 0.9,
    range: 1.0,
    critChance: 0.16,
    critMultiplier: 1.8,
  },
  gon: {
    id: "gon_earth_ground",
    name: "Earth Ground",
    koreanName: "대지포옹",
    englishName: "Earth's Embrace",
    romanized: "Daeji Po-ong",
    description: {
      korean: "대지같은 지면 기법",
      english: "Ground techniques like nurturing earth",
    },
    stance: "gon",
    type: "throw",
    damageType: "crushing",
    damageRange: { min: 24, max: 34, type: "crushing" },
    kiCost: 22,
    staminaCost: 20,
    executionTime: 450,
    recoveryTime: 600,
    accuracy: 0.84,
    range: 1.4,
    critChance: 0.12,
    critMultiplier: 1.6,
  },
};

// Main trigram data structure
export const TRIGRAM_DATA: Record<TrigramStance, TrigramData> = {
  geon: {
    stance: "geon",
    symbol: "☰",
    korean: "건",
    english: "Heaven",
    element: "Metal",
    philosophy: "Direct bone-striking force - 직접적인 골격 타격력",
    technique: TRIGRAM_TECHNIQUES.geon,
    color: KOREAN_COLORS.GEON_GOLD,
    kiCost: 5,
    transitionTime: 400,
    effectiveness: {
      geon: 1.0,
      tae: 1.2,
      li: 0.8,
      jin: 1.1,
      son: 0.9,
      gam: 1.0,
      gan: 0.7,
      gon: 1.3,
    },
  },
  tae: {
    stance: "tae",
    symbol: "☱",
    korean: "태",
    english: "Lake",
    element: "Water",
    philosophy: "Fluid joint manipulation - 유동적인 관절 조작",
    technique: TRIGRAM_TECHNIQUES.tae,
    color: KOREAN_COLORS.TAE_SILVER,
    kiCost: 5,
    transitionTime: 400,
    effectiveness: {
      geon: 0.8,
      tae: 1.0,
      li: 1.2,
      jin: 0.9,
      son: 1.1,
      gam: 1.3,
      gan: 1.0,
      gon: 0.7,
    },
  },
  li: {
    stance: "li",
    symbol: "☲",
    korean: "리",
    english: "Fire",
    element: "Fire",
    philosophy: "Precise nerve strikes - 정밀한 신경 타격",
    technique: TRIGRAM_TECHNIQUES.li,
    color: KOREAN_COLORS.LI_RED,
    kiCost: 5,
    transitionTime: 400,
    effectiveness: {
      geon: 1.2,
      tae: 0.8,
      li: 1.0,
      jin: 1.3,
      son: 0.7,
      gam: 0.9,
      gan: 1.1,
      gon: 1.0,
    },
  },
  jin: {
    stance: "jin",
    symbol: "☳",
    korean: "진",
    english: "Thunder",
    element: "Wood",
    philosophy: "Stunning techniques - 기절 기법",
    technique: TRIGRAM_TECHNIQUES.jin,
    color: KOREAN_COLORS.JIN_PURPLE,
    kiCost: 5,
    transitionTime: 400,
    effectiveness: {
      geon: 0.9,
      tae: 1.1,
      li: 0.7,
      jin: 1.0,
      son: 1.2,
      gam: 1.0,
      gan: 1.3,
      gon: 0.8,
    },
  },
  son: {
    stance: "son",
    symbol: "☴",
    korean: "손",
    english: "Wind",
    element: "Wood",
    philosophy: "Continuous pressure - 지속적인 압박",
    technique: TRIGRAM_TECHNIQUES.son,
    color: KOREAN_COLORS.SON_GREEN,
    kiCost: 5,
    transitionTime: 400,
    effectiveness: {
      geon: 1.1,
      tae: 0.9,
      li: 1.3,
      jin: 0.8,
      son: 1.0,
      gam: 1.2,
      gan: 0.7,
      gon: 1.0,
    },
  },
  gam: {
    stance: "gam",
    symbol: "☵",
    korean: "감",
    english: "Water",
    element: "Water",
    philosophy: "Blood flow restriction - 혈류 제한",
    technique: TRIGRAM_TECHNIQUES.gam,
    color: KOREAN_COLORS.GAM_BLUE,
    kiCost: 5,
    transitionTime: 400,
    effectiveness: {
      geon: 1.0,
      tae: 0.7,
      li: 1.1,
      jin: 1.0,
      son: 0.8,
      gam: 1.0,
      gan: 1.2,
      gon: 1.3,
    },
  },
  gan: {
    stance: "gan",
    symbol: "☶",
    korean: "간",
    english: "Mountain",
    element: "Earth",
    philosophy: "Defensive counters - 방어적 반격",
    technique: TRIGRAM_TECHNIQUES.gan,
    color: KOREAN_COLORS.GAN_BROWN,
    kiCost: 5,
    transitionTime: 400,
    effectiveness: {
      geon: 1.3,
      tae: 1.0,
      li: 0.9,
      jin: 0.7,
      son: 1.3,
      gam: 0.8,
      gan: 1.0,
      gon: 1.1,
    },
  },
  gon: {
    stance: "gon",
    symbol: "☷",
    korean: "곤",
    english: "Earth",
    element: "Earth",
    philosophy: "Ground techniques - 지면 기법",
    technique: TRIGRAM_TECHNIQUES.gon,
    color: KOREAN_COLORS.GON_DARK_BROWN,
    kiCost: 5,
    transitionTime: 400,
    effectiveness: {
      geon: 0.7,
      tae: 1.3,
      li: 1.0,
      jin: 1.2,
      son: 1.0,
      gam: 0.7,
      gan: 0.9,
      gon: 1.0,
    },
  },
};

// Stance effectiveness matrix
export const STANCE_EFFECTIVENESS_MATRIX: Record<
  TrigramStance,
  Record<TrigramStance, number>
> = {
  geon: {
    geon: 1.0,
    tae: 1.2,
    li: 0.8,
    jin: 1.1,
    son: 0.9,
    gam: 1.0,
    gan: 0.7,
    gon: 1.3,
  },
  tae: {
    geon: 0.8,
    tae: 1.0,
    li: 1.2,
    jin: 0.9,
    son: 1.1,
    gam: 1.3,
    gan: 1.0,
    gon: 0.7,
  },
  li: {
    geon: 1.2,
    tae: 0.8,
    li: 1.0,
    jin: 1.3,
    son: 0.7,
    gam: 0.9,
    gan: 1.1,
    gon: 1.0,
  },
  jin: {
    geon: 0.9,
    tae: 1.1,
    li: 0.7,
    jin: 1.0,
    son: 1.2,
    gam: 1.0,
    gan: 1.3,
    gon: 0.8,
  },
  son: {
    geon: 1.1,
    tae: 0.9,
    li: 1.3,
    jin: 0.8,
    son: 1.0,
    gam: 1.2,
    gan: 0.7,
    gon: 1.0,
  },
  gam: {
    geon: 1.0,
    tae: 0.7,
    li: 1.1,
    jin: 1.0,
    son: 0.8,
    gam: 1.0,
    gan: 1.2,
    gon: 1.3,
  },
  gan: {
    geon: 1.3,
    tae: 1.0,
    li: 0.9,
    jin: 0.7,
    son: 1.3,
    gam: 0.8,
    gan: 1.0,
    gon: 1.1,
  },
  gon: {
    geon: 0.7,
    tae: 1.3,
    li: 1.0,
    jin: 1.2,
    son: 1.0,
    gam: 0.7,
    gan: 0.9,
    gon: 1.0,
  },
};

// Trigram stances order
export const TRIGRAM_STANCES_ORDER: TrigramStance[] = [
  "geon",
  "tae",
  "li",
  "jin",
  "son",
  "gam",
  "gan",
  "gon",
];
