// filepath: /workspaces/blacktrigram/src/types/constants/trigram.ts
import type { TrigramStance } from "../enums";

// Eight Trigram stance order (팔괘 순서)
export const TRIGRAM_STANCES_ORDER = [
  "geon", // ☰ Heaven
  "tae", // ☱ Lake
  "li", // ☲ Fire
  "jin", // ☳ Thunder
  "son", // ☴ Wind
  "gam", // ☵ Water
  "gan", // ☶ Mountain
  "gon", // ☷ Earth
] as const satisfies readonly TrigramStance[];

// Trigram stance effectiveness matrix (팔괘 상성표)
export const STANCE_EFFECTIVENESS_MATRIX: Record<
  TrigramStance,
  Record<TrigramStance, number>
> = {
  geon: {
    geon: 1.0,
    tae: 1.1,
    li: 0.9,
    jin: 1.2,
    son: 0.8,
    gam: 1.1,
    gan: 0.9,
    gon: 1.3,
  },
  tae: {
    geon: 0.9,
    tae: 1.0,
    li: 1.2,
    jin: 0.8,
    son: 1.1,
    gam: 0.9,
    gan: 1.3,
    gon: 0.8,
  },
  li: {
    geon: 1.1,
    tae: 0.8,
    li: 1.0,
    jin: 0.9,
    son: 1.3,
    gam: 0.8,
    gan: 1.1,
    gon: 0.9,
  },
  jin: {
    geon: 0.8,
    tae: 1.2,
    li: 1.1,
    jin: 1.0,
    son: 0.9,
    gam: 1.3,
    gan: 0.8,
    gon: 1.1,
  },
  son: {
    geon: 1.2,
    tae: 0.9,
    li: 0.7,
    jin: 1.1,
    son: 1.0,
    gam: 1.1,
    gan: 1.3,
    gon: 0.8,
  },
  gam: {
    geon: 0.9,
    tae: 1.1,
    li: 1.2,
    jin: 0.7,
    son: 0.9,
    gam: 1.0,
    gan: 1.1,
    gon: 1.3,
  },
  gan: {
    geon: 1.1,
    tae: 0.7,
    li: 0.9,
    jin: 1.2,
    son: 0.7,
    gam: 0.9,
    gan: 1.0,
    gon: 1.1,
  },
  gon: {
    geon: 0.7,
    tae: 1.2,
    li: 1.1,
    jin: 0.9,
    son: 1.2,
    gam: 0.7,
    gan: 0.9,
    gon: 1.0,
  },
} as const;

// Create TRIGRAM_DATA export that components are expecting
export const TRIGRAM_DATA = {
  geon: {
    stance: "geon" as TrigramStance,
    korean: "건",
    english: "Heaven",
    symbol: "☰",
    element: "Metal",
    color: 0xffd700,
    philosophy: "Force, creativity, strength",
    preferredTechniques: ["천둥벽력", "무력투혼"],
    combatStyle: "Direct confrontation with overwhelming force",
    kiRegenRate: 1.2,
    order: 0,
    name: {
      korean: "건",
      english: "Heaven",
    },
    technique: {
      id: "geon_thunder_strike",
      name: "Heavenly Thunder Strike",
      koreanName: "천둥벽력",
      englishName: "Heavenly Thunder Strike",
      romanized: "cheondeungbyeokryeok",
      stance: "geon" as TrigramStance,
      type: "strike" as const,
      damageType: "blunt" as const,
      damage: 28,
      staminaCost: 15,
      kiCost: 10,
      accuracy: 0.85,
      range: 1.5,
      description: {
        korean: "하늘의 힘으로 적을 강타한다",
        english: "Strike with the force of heaven",
      },
    },
  },
  tae: {
    stance: "tae" as TrigramStance,
    korean: "태",
    english: "Lake",
    symbol: "☱",
    element: "Metal",
    color: 0x87ceeb,
    philosophy: "Joy, satisfaction, reflection",
    preferredTechniques: ["유수연타", "호수반격"],
    combatStyle: "Fluid and adaptive movements",
    kiRegenRate: 1.0,
    order: 1,
    name: {
      korean: "태",
      english: "Lake",
    },
    technique: {
      id: "tae_water_strike",
      name: "Flowing Water Strike",
      koreanName: "유수연타",
      englishName: "Flowing Water Strike",
      romanized: "yusuyeontta",
      stance: "tae" as TrigramStance,
      type: "strike" as const,
      damageType: "blunt" as const,
      damage: 22,
      staminaCost: 12,
      kiCost: 8,
      accuracy: 0.8,
      range: 1.2,
      description: {
        korean: "물처럼 흘러가며 연속 타격",
        english: "Continuous strikes flowing like water",
      },
    },
  },
  li: {
    stance: "li" as TrigramStance,
    korean: "리",
    english: "Fire",
    symbol: "☲",
    element: "Fire",
    color: 0xff4500,
    philosophy: "Clarity, intelligence, precision",
    preferredTechniques: ["화염지창", "정밀타격"],
    combatStyle: "Precise and intelligent strikes",
    kiRegenRate: 1.1,
    order: 2,
    name: {
      korean: "리",
      english: "Fire",
    },
    technique: {
      id: "li_flame_spear",
      name: "Flame Spear",
      koreanName: "화염지창",
      englishName: "Flame Spear",
      romanized: "hwayeomjichang",
      stance: "li" as TrigramStance,
      type: "strike" as const,
      damageType: "piercing" as const,
      damage: 26,
      staminaCost: 14,
      kiCost: 12,
      accuracy: 0.9,
      range: 1.8,
      description: {
        korean: "불꽃처럼 빠르고 정확한 창술",
        english: "Swift and precise spear technique like flame",
      },
    },
  },
  jin: {
    stance: "jin" as TrigramStance,
    korean: "진",
    english: "Thunder",
    symbol: "☳",
    element: "Wood",
    color: 0x9370db,
    philosophy: "Movement, initiative, shock",
    preferredTechniques: ["벽력일섬", "충격파동"],
    combatStyle: "Explosive and shocking attacks",
    kiRegenRate: 0.9,
    order: 3,
    name: {
      korean: "진",
      english: "Thunder",
    },
    technique: {
      id: "jin_lightning_flash",
      name: "Lightning Flash",
      koreanName: "벽력일섬",
      englishName: "Lightning Flash",
      romanized: "byeokllyeogilseom",
      stance: "jin" as TrigramStance,
      type: "strike" as const,
      damageType: "slashing" as const,
      damage: 30,
      staminaCost: 18,
      kiCost: 15,
      accuracy: 0.75,
      range: 1.4,
      description: {
        korean: "번개같이 빠른 일격",
        english: "Swift strike like lightning",
      },
    },
  },
  son: {
    stance: "son" as TrigramStance,
    korean: "손",
    english: "Wind",
    symbol: "☴",
    element: "Wood",
    color: 0x98fb98,
    philosophy: "Gentleness, penetration, progress",
    preferredTechniques: ["선풍연격", "바람술법"],
    combatStyle: "Gentle and penetrating movements",
    kiRegenRate: 1.1,
    order: 4,
    name: {
      korean: "손",
      english: "Wind",
    },
    technique: {
      id: "son_wind_strike",
      name: "Wind Continuous Strike",
      koreanName: "선풍연격",
      englishName: "Wind Continuous Strike",
      romanized: "seonpungyeongyeok",
      stance: "son" as TrigramStance,
      type: "strike" as const,
      damageType: "blunt" as const,
      damage: 20,
      staminaCost: 10,
      kiCost: 6,
      accuracy: 0.85,
      range: 1.3,
      description: {
        korean: "바람처럼 부드럽고 연속적인 타격",
        english: "Soft and continuous strikes like wind",
      },
    },
  },
  gam: {
    stance: "gam" as TrigramStance,
    korean: "감",
    english: "Water",
    symbol: "☵",
    element: "Water",
    color: 0x4169e1,
    philosophy: "Danger, depth, flowing",
    preferredTechniques: ["수류반격", "심연장법"],
    combatStyle: "Flowing and adaptive counter-attacks",
    kiRegenRate: 1.3,
    order: 5,
    name: {
      korean: "감",
      english: "Water",
    },
    technique: {
      id: "gam_water_counter",
      name: "Water Counter",
      koreanName: "수류반격",
      englishName: "Water Counter",
      romanized: "suryubangyeok",
      stance: "gam" as TrigramStance,
      type: "counter" as const,
      damageType: "blunt" as const,
      damage: 24,
      staminaCost: 12,
      kiCost: 10,
      accuracy: 0.88,
      range: 1.1,
      description: {
        korean: "물의 흐름으로 적의 공격을 역이용",
        english: "Counter using the flow of water",
      },
    },
  },
  gan: {
    stance: "gan" as TrigramStance,
    korean: "간",
    english: "Mountain",
    symbol: "☶",
    element: "Earth",
    color: 0x8b4513,
    philosophy: "Stillness, meditation, stopping",
    preferredTechniques: ["반석방어", "산악진법"],
    combatStyle: "Defensive and immovable stance",
    kiRegenRate: 0.8,
    order: 6,
    name: {
      korean: "간",
      english: "Mountain",
    },
    technique: {
      id: "gan_rock_defense",
      name: "Solid Rock Defense",
      koreanName: "반석방어",
      englishName: "Solid Rock Defense",
      romanized: "banseokbangeo",
      stance: "gan" as TrigramStance,
      type: "defense" as const,
      damageType: "blunt" as const,
      damage: 16,
      staminaCost: 8,
      kiCost: 5,
      accuracy: 0.95,
      range: 0.8,
      description: {
        korean: "바위처럼 견고한 방어 자세",
        english: "Solid defensive stance like a rock",
      },
    },
  },
  gon: {
    stance: "gon" as TrigramStance,
    korean: "곤",
    english: "Earth",
    symbol: "☷",
    element: "Earth",
    color: 0x654321,
    philosophy: "Receptivity, yielding, nurturing",
    preferredTechniques: ["대지포옹", "모대수법"],
    combatStyle: "Grounding and subduing techniques",
    kiRegenRate: 0.9,
    order: 7,
    name: {
      korean: "곤",
      english: "Earth",
    },
    technique: {
      id: "gon_earth_embrace",
      name: "Earth Embrace",
      koreanName: "대지포옹",
      englishName: "Earth Embrace",
      romanized: "daejipooong",
      stance: "gon" as TrigramStance,
      type: "grapple" as const,
      damageType: "blunt" as const,
      damage: 25,
      staminaCost: 16,
      kiCost: 12,
      accuracy: 0.8,
      range: 1.0,
      description: {
        korean: "대지의 힘으로 적을 감싸 제압",
        english: "Envelop and subdue with earth's power",
      },
    },
  },
} as const;
