/**
 * Trigram system constants for Black Trigram Korean martial arts
 */

import { KoreanTechnique } from "../combat";
import { PlayerArchetype, TrigramStance } from "../enums";
import type {
  TrigramData,
  TrigramEffectivenessMatrix,
  TrigramTheme,
} from "../trigram";
import { KOREAN_COLORS } from "./colors";
import { TrigramStance as TrigramStanceEnum } from "../enums"; // Assuming enum definition

// Helper function (optional, if you prefer this pattern)
// const createTrigram = (
//   id: TrigramStance,
//   korean: string,
//   english: string,
//   symbol: string,
//   description: string,
//   theme: TrigramTheme,
//   principle: string,
//   qualities: string[],
//   associatedTechniques: string[]
// ): TrigramData => ({
//   id,
//   korean,
//   english,
//   symbol,
//   description,
//   theme,
//   principle,
//   qualities,
//   associatedTechniques,
// });

// Order of Trigrams for UI elements like wheels or selection lists
export const TRIGRAM_STANCES_ORDER: readonly TrigramStance[] = [
  "geon" as TrigramStance,
  "tae" as TrigramStance,
  "li" as TrigramStance,
  "jin" as TrigramStance,
  "son" as TrigramStance,
  "gam" as TrigramStance,
  "gan" as TrigramStance,
  "gon" as TrigramStance,
] as const;

export const TRIGRAM_DATA: Record<TrigramStance, TrigramData> = {
  geon: {
    name: { korean: "건", english: "Heaven" },
    symbol: "☰",
    element: "metal",
    nature: "yang",
    philosophy: { korean: "하늘", english: "Heaven" },
    combat: { korean: "직접 공격", english: "Direct attack" },
    theme: {
      primary: KOREAN_COLORS.TRIGRAM_GEON_PRIMARY,
      secondary: KOREAN_COLORS.WHITE_SOLID,
    },
    defensiveBonus: 1.0,
    kiFlowModifier: 1.0,
    technique: {
      id: "geon_heaven_strike",
      name: "천둥벽력",
      koreanName: "천둥벽력",
      englishName: "Thunder Strike",
      stance: "geon",
      type: "strike",
      damageType: "blunt",
      damage: 30,
      kiCost: 15,
      staminaCost: 20,
      accuracy: 0.8,
      range: 1.2,
      executionTime: 800,
      recoveryTime: 1200,
      critChance: 0.1,
      critMultiplier: 1.5,
      effects: [],
      description: {
        korean: "하늘의 힘을 담은 직접적인 타격",
        english: "Direct strike imbued with heavenly power",
      },
    },
  },
  tae: {
    name: { korean: "태", english: "Lake" },
    symbol: "☱",
    element: "metal",
    nature: "yin",
    philosophy: { korean: "호수", english: "Lake" },
    combat: { korean: "유동적 적응", english: "Fluid adaptation" },
    theme: {
      primary: KOREAN_COLORS.TRIGRAM_TAE_PRIMARY,
      secondary: KOREAN_COLORS.UI_STEEL_GRAY,
    },
    defensiveBonus: 1.1,
    kiFlowModifier: 1.2,
    technique: {
      id: "tae_flowing_strikes",
      name: "유수연타",
      koreanName: "유수연타",
      englishName: "Flowing Strikes",
      stance: "tae",
      type: "strike",
      damageType: "blunt",
      damage: 25,
      kiCost: 12,
      staminaCost: 18,
      accuracy: 0.85,
      range: 1.0,
      executionTime: 600,
      recoveryTime: 1000,
      critChance: 0.08,
      critMultiplier: 1.3,
      effects: [],
      description: {
        korean: "물의 흐름처럼 연속적인 타격",
        english: "Continuous strikes like flowing water",
      },
    },
  },
  li: {
    name: { korean: "리", english: "Fire" },
    symbol: "☲",
    element: "metal",
    nature: "yang",
    philosophy: { korean: "불", english: "Fire" },
    combat: { korean: "접근 공격", english: "Close attack" },
    theme: {
      primary: KOREAN_COLORS.TRIGRAM_LI_PRIMARY,
      secondary: KOREAN_COLORS.ACCENT_RED,
    },
    defensiveBonus: 0.9,
    kiFlowModifier: 1.1,
    technique: {
      id: "li_flame_slash",
      name: "화염베기",
      koreanName: "화염베기",
      englishName: "Flame Slash",
      stance: "li",
      type: "strike",
      damageType: "slashing",
      damage: 35,
      kiCost: 18,
      staminaCost: 22,
      accuracy: 0.75,
      range: 1.1,
      executionTime: 700,
      recoveryTime: 1100,
      critChance: 0.12,
      critMultiplier: 1.6,
      effects: [],
      description: {
        korean: "불의 형상을 한 날카로운 베기",
        english: "A sharp slash in the form of fire",
      },
    },
  },
  jin: {
    name: { korean: "진", english: "Thunder" },
    symbol: "☳",
    element: "metal",
    nature: "yang",
    philosophy: { korean: "천둥", english: "Thunder" },
    combat: { korean: "돌진 공격", english: "Charge attack" },
    theme: {
      primary: KOREAN_COLORS.TRIGRAM_JIN_PRIMARY,
      secondary: KOREAN_COLORS.SECONDARY_YELLOW,
    },
    defensiveBonus: 0.8,
    kiFlowModifier: 1.3,
    technique: {
      id: "jin_thunder_clap",
      name: "천둥의 박치기",
      koreanName: "천둥의 박치기",
      englishName: "Thunder Clap",
      stance: "jin",
      type: "strike",
      damageType: "blunt",
      damage: 40,
      kiCost: 20,
      staminaCost: 25,
      accuracy: 0.78,
      range: 1.3,
      executionTime: 900,
      recoveryTime: 1300,
      critChance: 0.15,
      critMultiplier: 1.7,
      effects: [],
      description: {
        korean: "천둥의 힘으로 적을 가격",
        english: "Strike the enemy with the force of thunder",
      },
    },
  },
  son: {
    name: { korean: "손", english: "Wind" },
    symbol: "☴",
    element: "metal",
    nature: "yin",
    philosophy: { korean: "바람", english: "Wind" },
    combat: { korean: "회피 공격", english: "Evasive attack" },
    theme: {
      primary: KOREAN_COLORS.TRIGRAM_SON_PRIMARY,
      secondary: KOREAN_COLORS.POSITIVE_GREEN_DARK,
    },
    defensiveBonus: 1.2,
    kiFlowModifier: 0.9,
    technique: {
      id: "son_wind_cut",
      name: "바람베기",
      koreanName: "바람베기",
      englishName: "Wind Cut",
      stance: "son",
      type: "strike",
      damageType: "slashing",
      damage: 28,
      kiCost: 14,
      staminaCost: 19,
      accuracy: 0.82,
      range: 1.0,
      executionTime: 650,
      recoveryTime: 950,
      critChance: 0.09,
      critMultiplier: 1.4,
      effects: [],
      description: {
        korean: "바람의 힘으로 적을 베어내다",
        english: "Cut through the enemy with the power of wind",
      },
    },
  },
  gam: {
    name: { korean: "감", english: "Water" },
    symbol: "☵",
    element: "metal",
    nature: "yin",
    philosophy: { korean: "물", english: "Water" },
    combat: { korean: "유동 공격", english: "Flowing attack" },
    theme: {
      primary: KOREAN_COLORS.TRIGRAM_GAM_PRIMARY,
      secondary: KOREAN_COLORS.PRIMARY_BLUE_DARK,
    },
    defensiveBonus: 1.3,
    kiFlowModifier: 1.1,
    technique: {
      id: "gam_water_whip",
      name: "수륙재해",
      koreanName: "수륙재해",
      englishName: "Water Whip",
      stance: "gam",
      type: "strike",
      damageType: "blunt",
      damage: 27,
      kiCost: 13,
      staminaCost: 17,
      accuracy: 0.8,
      range: 1.4,
      executionTime: 700,
      recoveryTime: 1000,
      critChance: 0.1,
      critMultiplier: 1.5,
      effects: [],
      description: {
        korean: "물의 힘으로 적을 휘감아 타격",
        english: "Strike the enemy by wrapping them with the power of water",
      },
    },
  },
  gan: {
    name: { korean: "간", english: "Mountain" },
    symbol: "☶",
    element: "metal",
    nature: "yin",
    philosophy: { korean: "산", english: "Mountain" },
    combat: { korean: "방어 자세", english: "Defensive stance" },
    theme: {
      primary: KOREAN_COLORS.TRIGRAM_GAN_PRIMARY,
      secondary: KOREAN_COLORS.UI_STEEL_GRAY_DARK,
    },
    defensiveBonus: 1.4,
    kiFlowModifier: 0.8,
    technique: {
      id: "gan_mountain_guard",
      name: "산의 수호",
      koreanName: "산의 수호",
      englishName: "Mountain Guard",
      stance: "gan",
      type: "defense",
      damageType: "blunt",
      damage: 0,
      kiCost: 10,
      staminaCost: 15,
      accuracy: 1.0,
      range: 1.0,
      executionTime: 1000,
      recoveryTime: 1500,
      critChance: 0.0,
      critMultiplier: 1.0,
      effects: [],
      description: {
        korean: "산처럼 견고한 방어 자세",
        english: "A defensive stance as solid as a mountain",
      },
    },
  },
  gon: {
    name: { korean: "곤", english: "Earth" },
    symbol: "☷",
    element: "metal",
    nature: "yang",
    philosophy: { korean: "지구", english: "Earth" },
    combat: { korean: "포용 공격", english: "Embracing attack" },
    theme: {
      primary: KOREAN_COLORS.TRIGRAM_GON_PRIMARY,
      secondary: KOREAN_COLORS.SECONDARY_BROWN_DARK,
    },
    defensiveBonus: 1.1,
    kiFlowModifier: 1.2,
    technique: {
      id: "gon_earth_shield",
      name: "지구의 방패",
      koreanName: "지구의 방패",
      englishName: "Earth Shield",
      stance: "gon",
      type: "defense",
      damageType: "blunt",
      damage: 0,
      kiCost: 12,
      staminaCost: 16,
      accuracy: 1.0,
      range: 1.0,
      executionTime: 900,
      recoveryTime: 1400,
      critChance: 0.0,
      critMultiplier: 1.0,
      effects: [],
      description: {
        korean: "지구의 힘으로 적의 공격을 막다",
        english: "Block the enemy's attack with the power of earth",
      },
    },
  },
} as const;

// Stance Effectiveness Matrix (Example: Rock-Paper-Scissors style)
// Attacker Stance (row) vs Defender Stance (column)
// Value > 1.0: Attacker has advantage
// Value < 1.0: Attacker has disadvantage
// Value = 1.0: Neutral
export const STANCE_EFFECTIVENESS_MATRIX: Record<
  TrigramStance,
  Partial<Record<TrigramStance, number>>
> = {
  [TrigramStanceEnum.GEON]: {
    [TrigramStanceEnum.GON]: 1.2,
    [TrigramStanceEnum.SON]: 0.8,
  },
  [TrigramStanceEnum.TAE]: {
    [TrigramStanceEnum.JIN]: 1.2,
    [TrigramStanceEnum.GAN]: 0.8,
  },
  [TrigramStanceEnum.LI]: {
    [TrigramStanceEnum.GAM]: 1.2,
    [TrigramStanceEnum.TAE]: 0.8,
  },
  [TrigramStanceEnum.JIN]: {
    [TrigramStanceEnum.SON]: 1.2,
    [TrigramStanceEnum.GEON]: 0.8,
  },
  [TrigramStanceEnum.SON]: {
    [TrigramStanceEnum.GON]: 1.2,
    [TrigramStanceEnum.LI]: 0.8,
  },
  [TrigramStanceEnum.GAM]: {
    [TrigramStanceEnum.LI]: 1.2,
    [TrigramStanceEnum.JIN]: 0.8,
  },
  [TrigramStanceEnum.GAN]: {
    [TrigramStanceEnum.TAE]: 1.2,
    [TrigramStanceEnum.GAM]: 0.8,
  },
  [TrigramStanceEnum.GON]: {
    [TrigramStanceEnum.GEON]: 1.2,
    [TrigramStanceEnum.SON]: 0.8,
  },
  // Fill in other relationships or assume 1.0 for unspecified pairs
};
