// Anatomical regions mapping for Korean martial arts vital point system
import type { BodyRegion } from "../../types";
import type { RegionData } from "../../types/anatomy";

// All vital points referenced by string ID, matching VITAL_POINTS_DATA
export const ANATOMICAL_REGIONS_DATA: Readonly<Record<BodyRegion, RegionData>> =
  {
    head: {
      name: { korean: "머리", english: "Head" },
      subRegions: [
        "face_upper",
        "temples",
        "occiput",
        "eyes",
        "nose",
        "jaw",
        "philtrum",
      ],
      vitalPoints: [
        "injoong",
        "kanjanori",
        "baihui",
        "yintang",
        "taiyang",
        "eye_socket",
        "bridge_of_nose",
        "jaw_point_mandible",
        "chin_menton",
        "mastoid_process",
        "occiput_base",
      ],
      vulnerability: 1.5,
      pressure_points: [
        "baihui",
        "yintang",
        "taiyang",
        "eye_socket",
        "philtrum",
      ],
    },
    face_upper: {
      name: { korean: "얼굴 상부", english: "Upper Face" },
      subRegions: ["eyes", "nose", "philtrum"],
      vitalPoints: ["eye_socket", "bridge_of_nose", "yintang", "injoong"],
      vulnerability: 1.3,
      pressure_points: ["eye_socket", "philtrum"],
    },
    chest: {
      name: { korean: "가슴", english: "Chest" },
      vitalPoints: [
        "sternum_center",
        "clavicle_notch",
        "clavicle_midpoint",
        "jugular_notch",
        "sternoclavicular_joint",
      ],
      vulnerability: 1.1,
      pressure_points: ["sternum_center"],
    },
    abdomen: {
      name: { korean: "복부", english: "Abdomen" },
      vitalPoints: ["solar_plexus", "liver_area", "spleen_area", "umbilicus"],
      vulnerability: 1.3,
      pressure_points: ["solar_plexus", "umbilicus"],
    },
    neck: {
      name: { korean: "목", english: "Neck" },
      vitalPoints: ["neck_carotid", "larynx", "jugular_notch"],
      vulnerability: 1.8,
      pressure_points: ["neck_carotid"],
    },
    torso: {
      name: { korean: "몸통", english: "Torso" },
      subRegions: ["chest", "abdomen"],
      vitalPoints: [
        "sternum_center",
        "clavicle_notch",
        "solar_plexus",
        "ribs_floating",
        "kidney_area",
        "spine_cervical",
        "spine_thoracic",
        "spine_lumbar",
        "liver_area",
        "spleen_area",
        "costal_margin",
        "sternum_manubrium",
        "xiphoid_process",
        "diaphragm",
        "kidney_left",
        "kidney_right",
        "scapula",
        "spine_sacral",
        "spine_coccyx",
      ],
      vulnerability: 1.0,
      pressure_points: ["solar_plexus", "umbilicus"],
    },
    left_arm: {
      name: { korean: "왼팔", english: "Left Arm" },
      subRegions: ["hand"],
      vitalPoints: [
        "bicep_radial_nerve",
        "elbow_joint_ulnar",
        "wrist_radial_artery_left",
        "shoulder_joint",
        "elbow_joint_general",
        "wrist_joint",
        "hand_palm_center",
        "back_of_hand",
        "finger_pip_joint",
        "thumb_joint",
        "metacarpal_bone",
        "carpal_bones",
        "radial_styloid_process",
        "ulnar_styloid_process",
        "biceps_tendon",
        "brachial_artery",
        "cubital_fossa",
        "deltoid_insertion",
        "axilla",
        "median_nerve_wrist",
        "knuckles_base",
        "thumb_webbing",
      ],
      vulnerability: 1.0,
      pressure_points: [
        "elbow_joint_ulnar",
        "wrist_radial_artery_left",
        "thumb_webbing",
      ],
    },
    right_arm: {
      name: { korean: "오른팔", english: "Right Arm" },
      subRegions: ["hand"],
      vitalPoints: [
        "wrist_radial_artery_right",
        "shoulder_joint",
        "elbow_joint_general",
        "wrist_joint",
        "hand_palm_center",
        "back_of_hand",
        "finger_pip_joint",
        "thumb_joint",
        "metacarpal_bone",
        "carpal_bones",
        "radial_styloid_process",
        "ulnar_styloid_process",
        "biceps_tendon",
        "brachial_artery",
        "cubital_fossa",
        "deltoid_insertion",
        "axilla",
        "median_nerve_wrist",
        "knuckles_base",
        "thumb_webbing",
      ],
      vulnerability: 1.0,
      pressure_points: ["wrist_radial_artery_right", "thumb_webbing"],
    },
    left_leg: {
      name: { korean: "왼다리", english: "Left Leg" },
      subRegions: ["foot"],
      vitalPoints: [
        "ankle_achilles_left",
        "femoral_artery_thigh",
        "knee_peroneal_nerve",
        "greater_trochanter",
        "femur_shaft",
        "patella",
        "knee_joint_medial",
        "knee_joint_lateral",
        "popliteal_fossa",
        "tibial_tuberosity",
        "tibial_nerve",
        "tibia_shin",
        "fibula_head",
        "ankle_joint_general",
        "medial_malleolus",
        "lateral_malleolus",
        "plantar_fascia",
        "metatarsal_bones",
        "toe_proximal_joint",
        "big_toe_ip_joint",
        "instep_top",
        "ball_of_foot",
      ],
      vulnerability: 1.0,
      pressure_points: [
        "femoral_artery_thigh",
        "popliteal_fossa",
        "instep_top",
      ],
    },
    right_leg: {
      name: { korean: "오른다리", english: "Right Leg" },
      subRegions: ["foot"],
      vitalPoints: [
        "ankle_achilles_right",
        "femoral_artery_thigh",
        "knee_peroneal_nerve",
        "greater_trochanter",
        "femur_shaft",
        "patella",
        "knee_joint_medial",
        "knee_joint_lateral",
        "popliteal_fossa",
        "tibial_tuberosity",
        "tibial_nerve",
        "tibia_shin",
        "fibula_head",
        "ankle_joint_general",
        "medial_malleolus",
        "lateral_malleolus",
        "plantar_fascia",
        "metatarsal_bones",
        "toe_proximal_joint",
        "big_toe_ip_joint",
        "instep_top",
        "ball_of_foot",
      ],
      vulnerability: 1.0,
      pressure_points: ["ankle_achilles_right", "instep_top"],
    },
  };
