// Anatomical regions mapping for Korean martial arts vital point system
// Import the canonical RegionData type from the type system
import type { BodyRegion } from "../../types";

// Use the canonical RegionData interface from anatomy.ts
import type { RegionData } from "../../types/anatomy";

// The data is already correctly structured with pressure_points,
// but ensure all regions have this property defined
export const ANATOMICAL_REGIONS_DATA: Readonly<Record<BodyRegion, RegionData>> =
  {
    head: {
      name: { korean: "머리", english: "Head" },
      subRegions: ["face_upper", "temples", "occiput"] as const,
      vitalPoints: ["head_temple", "philtrum", "mastoid_process"] as const,
      vulnerability: 1.5,
      pressure_points: ["baihui", "yintang", "taiyang"] as const,
    },
    face_upper: {
      name: { korean: "얼굴 상부", english: "Upper Face" },
      subRegions: ["eyes", "nose"] as const,
      vitalPoints: ["eye_socket", "bridge_of_nose"] as const,
      vulnerability: 1.3,
      pressure_points: ["eye_socket"] as const,
    },
    neck: {
      name: { korean: "목", english: "Neck" },
      subRegions: [] as const,
      vitalPoints: ["neck_carotid", "larynx"] as const,
      vulnerability: 1.8,
      pressure_points: ["neck_carotid"] as const,
    },
    torso: {
      name: { korean: "몸통", english: "Torso" },
      subRegions: ["chest", "abdomen", "back"] as const,
      vitalPoints: ["solar_plexus", "ribs_floating", "kidney_area"] as const,
      vulnerability: 1.0,
      pressure_points: ["solar_plexus", "zhongwan", "qihai"] as const,
    },
    chest: {
      name: { korean: "가슴", english: "Chest" },
      subRegions: [] as const,
      vitalPoints: ["sternum_center", "clavicle_notch"] as const,
      vulnerability: 1.1,
      pressure_points: ["sternum_center", "shanzhong", "qimen"] as const,
    },
    abdomen: {
      name: { korean: "복부", english: "Abdomen" },
      subRegions: [] as const,
      vitalPoints: ["solar_plexus", "liver_area", "spleen_area"] as const,
      vulnerability: 1.2,
      pressure_points: ["solar_plexus"] as const,
    },
    back: {
      name: { korean: "등", english: "Back" },
      subRegions: ["upper_back", "lower_back"] as const,
      vitalPoints: ["spine_cervical", "spine_thoracic", "kidney_area"] as const,
      vulnerability: 0.9,
      pressure_points: ["kidney_area"] as const,
    },
    upper_back: {
      name: { korean: "등 상부", english: "Upper Back" },
      subRegions: [] as const,
      vitalPoints: ["spine_thoracic"] as const,
      vulnerability: 0.8,
      pressure_points: [] as const,
    },
    lower_back: {
      name: { korean: "등 하부", english: "Lower Back" },
      subRegions: [] as const,
      vitalPoints: ["spine_lumbar", "kidney_area"] as const,
      vulnerability: 1.0,
      pressure_points: ["kidney_area"] as const,
    },
    limbs: {
      name: { korean: "팔다리", english: "Limbs" },
      subRegions: ["arms", "legs"] as const,
      vitalPoints: [] as const,
      vulnerability: 0.9,
      pressure_points: [] as const,
    },
    arms: {
      name: { korean: "팔", english: "Arms" },
      subRegions: ["left_arm", "right_arm"] as const,
      vitalPoints: ["bicep_radial_nerve", "elbow_joint_ulnar"] as const,
      vulnerability: 1.0,
      pressure_points: ["elbow_joint_ulnar"] as const,
    },
    left_arm: {
      name: { korean: "왼팔", english: "Left Arm" },
      subRegions: [] as const,
      vitalPoints: ["wrist_radial_artery_left"] as const,
      vulnerability: 1.0,
      pressure_points: ["wrist_radial_artery_left"] as const,
    },
    right_arm: {
      name: { korean: "오른팔", english: "Right Arm" },
      subRegions: [] as const,
      vitalPoints: ["wrist_radial_artery_right"] as const,
      vulnerability: 1.0,
      pressure_points: ["wrist_radial_artery_right"] as const,
    },
    legs: {
      name: { korean: "다리", english: "Legs" },
      subRegions: ["left_leg", "right_leg"] as const,
      vitalPoints: ["femoral_artery_thigh", "knee_peroneal_nerve"] as const,
      vulnerability: 1.0,
      pressure_points: ["femoral_artery_thigh"] as const,
    },
    left_leg: {
      name: { korean: "왼다리", english: "Left Leg" },
      subRegions: [] as const,
      vitalPoints: ["ankle_achilles_left"] as const,
      vulnerability: 1.0,
      pressure_points: ["ankle_achilles_left"] as const,
    },
    right_leg: {
      name: { korean: "오른다리", english: "Right Leg" },
      subRegions: [] as const,
      vitalPoints: ["ankle_achilles_right"] as const,
      vulnerability: 1.0,
      pressure_points: ["ankle_achilles_right"] as const,
    },
    hands: {
      name: { korean: "손", english: "Hands" },
      subRegions: [] as const,
      vitalPoints: ["knuckles_base", "thumb_webbing"] as const,
      vulnerability: 1.2,
      pressure_points: ["thumb_webbing"] as const,
    },
    feet: {
      name: { korean: "발", english: "Feet" },
      subRegions: [] as const,
      vitalPoints: ["instep_top", "ball_of_foot"] as const,
      vulnerability: 1.1,
      pressure_points: ["instep_top"] as const,
    },
    joints: {
      name: { korean: "관절", english: "Joints" },
      subRegions: [] as const,
      vitalPoints: [
        "elbow_joint_ulnar",
        "knee_joint_patella",
        "shoulder_joint_capsule",
      ] as const,
      vulnerability: 1.4,
      pressure_points: ["elbow_joint_ulnar", "knee_joint_patella"] as const,
    },
    head_side: {
      name: { korean: "머리 측면", english: "Side of Head" },
      subRegions: [] as const,
      vitalPoints: ["head_temple"] as const,
      vulnerability: 1.6,
      pressure_points: ["head_temple"] as const,
    },
    upper_abdomen_center: {
      name: { korean: "상복부 중앙", english: "Upper Abdomen Center" },
      subRegions: [] as const,
      vitalPoints: ["solar_plexus"] as const,
      vulnerability: 1.7,
      pressure_points: ["solar_plexus"] as const,
    },
    eyes: {
      name: { korean: "눈", english: "Eyes" },
      subRegions: [] as const,
      vitalPoints: ["eye_socket"] as const,
      vulnerability: 2.0,
      pressure_points: ["eye_socket"] as const,
    },
    nose: {
      name: { korean: "코", english: "Nose" },
      subRegions: [] as const,
      vitalPoints: ["bridge_of_nose", "philtrum"] as const,
      vulnerability: 1.5,
      pressure_points: ["philtrum"] as const,
    },
    jaw: {
      name: { korean: "턱", english: "Jaw" },
      subRegions: [] as const,
      vitalPoints: ["jaw_point_mandible", "chin_menton"] as const,
      vulnerability: 1.4,
      pressure_points: ["jaw_point_mandible"] as const,
    },
    temples: {
      name: { korean: "관자놀이", english: "Temples" },
      subRegions: [] as const,
      vitalPoints: ["head_temple"] as const,
      vulnerability: 1.8,
      pressure_points: ["head_temple"] as const,
    },
    philtrum: {
      name: { korean: "인중", english: "Philtrum" },
      subRegions: [] as const,
      vitalPoints: ["philtrum"] as const,
      vulnerability: 1.9,
      pressure_points: ["philtrum"] as const,
    },
    mastoid_process: {
      name: { korean: "유돌", english: "Mastoid Process" },
      subRegions: [] as const,
      vitalPoints: ["mastoid_process"] as const,
      vulnerability: 1.6,
      pressure_points: ["mastoid_process"] as const,
    },
    occiput: {
      name: { korean: "후두골", english: "Occiput" },
      subRegions: [] as const,
      vitalPoints: ["occiput_base"] as const,
      vulnerability: 1.7,
      pressure_points: ["occiput_base"] as const,
    },
    ribs: {
      name: { korean: "갈비뼈", english: "Ribs" },
      subRegions: [] as const,
      vitalPoints: ["ribs_floating", "rib_cartilage_junction"] as const,
      vulnerability: 1.2,
      pressure_points: ["ribs_floating"] as const,
    },
    clavicle: {
      name: { korean: "쇄골", english: "Clavicle" },
      subRegions: [] as const,
      vitalPoints: ["clavicle_notch", "clavicle_midpoint"] as const,
      vulnerability: 1.5,
      pressure_points: ["clavicle_notch"] as const,
    },
    solar_plexus: {
      name: { korean: "명치", english: "Solar Plexus" },
      subRegions: [] as const,
      vitalPoints: ["solar_plexus"] as const,
      vulnerability: 1.8,
      pressure_points: ["solar_plexus"] as const,
    },
    kidneys: {
      name: { korean: "신장", english: "Kidneys" },
      subRegions: [] as const,
      vitalPoints: ["kidney_area"] as const,
      vulnerability: 1.7,
      pressure_points: ["kidney_area"] as const,
    },
    liver: {
      name: { korean: "간", english: "Liver" },
      subRegions: [] as const,
      vitalPoints: ["liver_area"] as const,
      vulnerability: 1.6,
      pressure_points: ["liver_area"] as const,
    },
    spleen: {
      name: { korean: "비장", english: "Spleen" },
      subRegions: [] as const,
      vitalPoints: ["spleen_area"] as const,
      vulnerability: 1.6,
      pressure_points: ["spleen_area"] as const,
    },
    floating_ribs: {
      name: { korean: "뜬갈비뼈", english: "Floating Ribs" },
      subRegions: [] as const,
      vitalPoints: ["ribs_floating"] as const,
      vulnerability: 1.4,
      pressure_points: ["ribs_floating"] as const,
    },
    face: {
      name: { korean: "얼굴", english: "Face" },
      subRegions: ["face_upper", "eyes", "nose", "jaw", "philtrum"] as const,
      vitalPoints: [
        "eye_socket",
        "bridge_of_nose",
        "jaw_point_mandible",
        "philtrum",
      ] as const,
      vulnerability: 1.5,
      pressure_points: ["philtrum", "eye_socket"] as const,
    },
    leg_back_knee: {
      name: { korean: "무릎 뒤", english: "Back of Knee" },
      subRegions: [] as const,
      vitalPoints: ["popliteal_fossa", "knee_back_nerve"] as const,
      vulnerability: 1.6,
      pressure_points: ["popliteal_fossa"] as const,
    },
    throat: {
      name: { korean: "목구멍", english: "Throat" },
      subRegions: [] as const,
      vitalPoints: [] as const,
      vulnerability: 1.0,
      pressure_points: [] as const,
    },
    general: {
      name: { korean: "일반", english: "General" },
      subRegions: [] as const,
      vitalPoints: [] as const,
      vulnerability: 1.0,
      pressure_points: [] as const,
    },
    internal: {
      name: { korean: "내부", english: "Internal" },
      subRegions: [] as const,
      vitalPoints: [] as const,
      vulnerability: 1.0,
      pressure_points: [] as const,
    },
    pressure_points: {
      name: { korean: "혈자리", english: "Pressure Points" },
      subRegions: [] as const,
      vitalPoints: [
        "head_philtrum_injoong",
        "vp_solar_plexus_myungchi",
        "head_temple_kanjanori",
      ] as const,
      vulnerability: 1.3,
      pressure_points: ["hegu", "taichong", "zusanli"] as const,
    },
  } as const;

// Export the type for use elsewhere if needed
export type { RegionData } from "../../types/anatomy";
