// Korean vital points for Black Trigram (흑괘)
// Complete, culturally accurate, bilingual (Korean, English, Romanization)
import type { VitalPoint } from "../../types/anatomy";
import type { KoreanText } from "../../types/korean-text";

// Utility for KoreanText
const k = (korean: string, english: string): KoreanText => ({
  korean,
  english,
});

export const VITAL_POINTS_DATA: readonly VitalPoint[] = [
  // 1. 인중 (Philtrum)
  {
    id: "injoong",
    name: k("인중", "Philtrum"),
    koreanName: "인중",
    englishName: "Philtrum",
    category: "head",
    description: k("코와 입술 사이의 홈", "Groove between nose and upper lip"),
    location: { x: 50, y: 15, region: "face_upper" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 18,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["pressure_point", "nerve_strike"],
  },
  // 2. 관자놀이 (Temple)
  {
    id: "kanjanori",
    name: k("관자놀이", "Temple"),
    koreanName: "관자놀이",
    englishName: "Temple",
    category: "head",
    description: k(
      "머리 측면의 약한 부위",
      "Weak area on the side of the head"
    ),
    location: { x: 70, y: 18, region: "head_side" },
    severity: "critical",
    baseAccuracy: 0.7,
    baseDamage: 22,
    damageMultiplier: 2.0,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 3. 백회 (Crown Point)
  {
    id: "baihui",
    name: k("백회", "Crown Point"),
    koreanName: "백회",
    englishName: "Crown Point",
    category: "head",
    description: k("정수리 중앙 혈자리", "Crown of the head acupoint"),
    location: { x: 50, y: 5, region: "head" },
    severity: "severe",
    baseAccuracy: 0.8,
    baseDamage: 20,
    damageMultiplier: 1.8,
    effects: [],
    techniques: ["pressure_point"],
  },
  // 4. 인당 (Glabella)
  {
    id: "yintang",
    name: k("인당", "Glabella"),
    koreanName: "인당",
    englishName: "Glabella",
    category: "head",
    description: k("미간 중앙 혈자리", "Acupoint between the eyebrows"),
    location: { x: 50, y: 12, region: "face_upper" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 12,
    damageMultiplier: 1.4,
    effects: [],
    techniques: ["pressure_point"],
  },
  // 5. 태양 (Sun Point)
  {
    id: "taiyang",
    name: k("태양", "Sun Point"),
    koreanName: "태양",
    englishName: "Sun Point",
    category: "head",
    description: k("관자놀이 부근 혈자리", "Acupoint near the temple"),
    location: { x: 80, y: 20, region: "head_side" },
    severity: "critical",
    baseAccuracy: 0.7,
    baseDamage: 24,
    damageMultiplier: 2.1,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 6. 안와 (Eye Socket)
  {
    id: "eye_socket",
    name: k("안와", "Eye Socket"),
    koreanName: "안와",
    englishName: "Eye Socket",
    category: "head",
    description: k("눈 주위 뼈", "Bone around the eye"),
    location: { x: 60, y: 18, region: "eyes" },
    severity: "critical",
    baseAccuracy: 0.6,
    baseDamage: 28,
    damageMultiplier: 2.2,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 7. 콧대 (Bridge of Nose)
  {
    id: "bridge_of_nose",
    name: k("콧대", "Bridge of Nose"),
    koreanName: "콧대",
    englishName: "Bridge of Nose",
    category: "head",
    description: k("코의 윗부분 뼈", "Upper bony part of the nose"),
    location: { x: 50, y: 20, region: "nose" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 16,
    damageMultiplier: 1.6,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 8. 하악각 (Mandible Angle)
  {
    id: "jaw_point_mandible",
    name: k("하악각", "Mandible Angle"),
    koreanName: "하악각",
    englishName: "Mandible Angle",
    category: "head",
    description: k("턱뼈의 각진 부분", "Angle of the jawbone"),
    location: { x: 40, y: 30, region: "jaw" },
    severity: "severe",
    baseAccuracy: 0.8,
    baseDamage: 20,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 9. 이하 (Chin - Menton)
  {
    id: "chin_menton",
    name: k("이하", "Chin (Menton)"),
    koreanName: "이하",
    englishName: "Chin (Menton)",
    category: "head",
    description: k("턱 끝 부분", "Tip of the chin"),
    location: { x: 50, y: 35, region: "jaw" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 14,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["strike"],
  },
  // 10. 유돌 (Mastoid Process)
  {
    id: "mastoid_process",
    name: k("유돌", "Mastoid Process"),
    koreanName: "유돌",
    englishName: "Mastoid Process",
    category: "head",
    description: k("귀 뒤쪽 돌출 뼈", "Bony protrusion behind the ear"),
    location: { x: 80, y: 25, region: "head_side" },
    severity: "severe",
    baseAccuracy: 0.8,
    baseDamage: 18,
    damageMultiplier: 1.6,
    effects: [],
    techniques: ["strike"],
  },
  // 11. 후두골 (Occiput Base)
  {
    id: "occiput_base",
    name: k("후두골", "Occiput Base"),
    koreanName: "후두골",
    englishName: "Occiput Base",
    category: "head",
    description: k("머리 뒤쪽 아래 뼈", "Lower back of the skull"),
    location: { x: 50, y: 5, region: "occiput" },
    severity: "critical",
    baseAccuracy: 0.7,
    baseDamage: 25,
    damageMultiplier: 2.0,
    effects: [],
    techniques: ["strike"],
  },
  // 12. 경동맥 (Carotid Artery)
  {
    id: "neck_carotid",
    name: k("경동맥", "Carotid Artery"),
    koreanName: "경동맥",
    englishName: "Carotid Artery",
    category: "neck",
    description: k("목의 주요 동맥", "Major artery in the neck"),
    location: { x: 55, y: 40, region: "neck" },
    severity: "critical",
    baseAccuracy: 0.7,
    baseDamage: 30,
    damageMultiplier: 2.3,
    effects: [],
    techniques: ["pressure_point", "nerve_strike"],
  },
  // 13. 후두 (Larynx)
  {
    id: "larynx",
    name: k("후두", "Larynx"),
    koreanName: "후두",
    englishName: "Larynx",
    category: "neck",
    description: k("목의 발성 기관", "Voice box in the neck"),
    location: { x: 50, y: 45, region: "neck" },
    severity: "severe",
    baseAccuracy: 0.8,
    baseDamage: 22,
    damageMultiplier: 1.8,
    effects: [],
    techniques: ["strike"],
  },
  // 14. 흉골 중앙 (Sternum Center)
  {
    id: "sternum_center",
    name: k("흉골 중앙", "Sternum Center"),
    koreanName: "흉골 중앙",
    englishName: "Sternum Center",
    category: "torso",
    description: k("가슴뼈 중앙", "Center of the breastbone"),
    location: { x: 50, y: 55, region: "chest" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 15,
    damageMultiplier: 1.2,
    effects: [],
    techniques: ["strike"],
  },
  // 15. 쇄골 패임 (Clavicle Notch)
  {
    id: "clavicle_notch",
    name: k("쇄골 패임", "Clavicle Notch"),
    koreanName: "쇄골 패임",
    englishName: "Clavicle Notch",
    category: "torso",
    description: k(
      "쇄골 중앙의 오목한 부위",
      "Hollow at the center of the collarbone"
    ),
    location: { x: 50, y: 48, region: "chest" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 13,
    damageMultiplier: 1.1,
    effects: [],
    techniques: ["pressure_point"],
  },
  // 16. 명치 (Solar Plexus)
  {
    id: "solar_plexus",
    name: k("명치", "Solar Plexus"),
    koreanName: "명치",
    englishName: "Solar Plexus",
    category: "torso",
    description: k(
      "복부 상부의 신경 다발",
      "Nerve bundle in the upper abdomen"
    ),
    location: { x: 50, y: 65, region: "upper_abdomen_center" },
    severity: "critical",
    baseAccuracy: 0.8,
    baseDamage: 28,
    damageMultiplier: 2.0,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 17. 뜬갈비뼈 (Floating Ribs)
  {
    id: "ribs_floating",
    name: k("뜬갈비뼈", "Floating Ribs"),
    koreanName: "뜬갈비뼈",
    englishName: "Floating Ribs",
    category: "torso",
    description: k(
      "가장 아래쪽 갈비뼈",
      "Lowest ribs not attached to the sternum"
    ),
    location: { x: 60, y: 70, region: "ribs" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 20,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["strike"],
  },
  // 18. 신장 부위 (Kidney Area)
  {
    id: "kidney_area",
    name: k("신장 부위", "Kidney Area"),
    koreanName: "신장 부위",
    englishName: "Kidney Area",
    category: "torso",
    description: k("등 하부의 신장 위치", "Kidney location in the lower back"),
    location: { x: 40, y: 75, region: "lower_back" },
    severity: "critical",
    baseAccuracy: 0.75,
    baseDamage: 26,
    damageMultiplier: 2.1,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 19. 경추 (Cervical Spine)
  {
    id: "spine_cervical",
    name: k("경추", "Cervical Spine"),
    koreanName: "경추",
    englishName: "Cervical Spine",
    category: "torso",
    description: k("목 부분의 척추", "Neck portion of the spine"),
    location: { x: 50, y: 40, region: "neck" },
    severity: "critical",
    baseAccuracy: 0.7,
    baseDamage: 30,
    damageMultiplier: 2.2,
    effects: [],
    techniques: ["strike"],
  },
  // 20. 흉추 (Thoracic Spine)
  {
    id: "spine_thoracic",
    name: k("흉추", "Thoracic Spine"),
    koreanName: "흉추",
    englishName: "Thoracic Spine",
    category: "torso",
    description: k("등 중간의 척추", "Middle back portion of the spine"),
    location: { x: 50, y: 60, region: "upper_back" },
    severity: "severe",
    baseAccuracy: 0.8,
    baseDamage: 22,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["strike"],
  },
  // 21. 요추 (Lumbar Spine)
  {
    id: "spine_lumbar",
    name: k("요추", "Lumbar Spine"),
    koreanName: "요추",
    englishName: "Lumbar Spine",
    category: "torso",
    description: k("허리 부분의 척추", "Lower back portion of the spine"),
    location: { x: 50, y: 80, region: "lower_back" },
    severity: "severe",
    baseAccuracy: 0.8,
    baseDamage: 22,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["strike"],
  },
  // 22. 상완 요골 신경 (Radial Nerve - Upper Arm)
  {
    id: "bicep_radial_nerve",
    name: k("상완 요골 신경", "Radial Nerve (Upper Arm)"),
    koreanName: "상완 요골 신경",
    englishName: "Radial Nerve (Upper Arm)",
    category: "nerve",
    description: k("상완의 주요 신경", "Major nerve in the upper arm"),
    location: { x: 30, y: 55, region: "arms" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 18,
    damageMultiplier: 1.6,
    effects: [],
    techniques: ["nerve_strike"],
  },
  // 23. 팔꿈치 척골 신경 (Ulnar Nerve - Elbow)
  {
    id: "elbow_joint_ulnar",
    name: k("팔꿈치 척골 신경", "Ulnar Nerve (Elbow)"),
    koreanName: "팔꿈치 척골 신경",
    englishName: "Ulnar Nerve (Elbow)",
    category: "nerve",
    description: k("팔꿈치의 척골 신경", "Ulnar nerve at the elbow"),
    location: { x: 25, y: 60, region: "arms" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 14,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["nerve_strike", "pressure_point"],
  },
  // 24. 왼쪽 요골 동맥 (Radial Artery - Left Wrist)
  {
    id: "wrist_radial_artery_left",
    name: k("왼쪽 요골 동맥", "Radial Artery (Left Wrist)"),
    koreanName: "왼쪽 요골 동맥",
    englishName: "Radial Artery (Left Wrist)",
    category: "vascular",
    description: k("왼쪽 손목의 주요 동맥", "Major artery in the left wrist"),
    location: { x: 20, y: 90, region: "left_arm" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 18,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["pressure_point"],
  },
  // 25. 오른쪽 요골 동맥 (Radial Artery - Right Wrist)
  {
    id: "wrist_radial_artery_right",
    name: k("오른쪽 요골 동맥", "Radial Artery (Right Wrist)"),
    koreanName: "오른쪽 요골 동맥",
    englishName: "Radial Artery (Right Wrist)",
    category: "vascular",
    description: k(
      "오른쪽 손목의 주요 동맥",
      "Major artery in the right wrist"
    ),
    location: { x: 80, y: 90, region: "right_arm" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 18,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["pressure_point"],
  },
  // 26. 대퇴 동맥 (Femoral Artery)
  {
    id: "femoral_artery_thigh",
    name: k("대퇴 동맥", "Femoral Artery"),
    koreanName: "대퇴 동맥",
    englishName: "Femoral Artery",
    category: "vascular",
    description: k("허벅지의 주요 동맥", "Major artery in the thigh"),
    location: { x: 50, y: 95, region: "legs" },
    severity: "critical",
    baseAccuracy: 0.7,
    baseDamage: 30,
    damageMultiplier: 2.2,
    effects: [],
    techniques: ["pressure_point"],
  },
  // 27. 무릎 종아리 신경 (Peroneal Nerve - Knee)
  {
    id: "knee_peroneal_nerve",
    name: k("무릎 종아리 신경", "Peroneal Nerve (Knee)"),
    koreanName: "무릎 종아리 신경",
    englishName: "Peroneal Nerve (Knee)",
    category: "nerve",
    description: k("무릎 외측의 신경", "Nerve on the outer side of the knee"),
    location: { x: 50, y: 85, region: "legs" },
    severity: "severe",
    baseAccuracy: 0.8,
    baseDamage: 20,
    damageMultiplier: 1.6,
    effects: [],
    techniques: ["nerve_strike"],
  },
  // 28. 왼쪽 아킬레스건 (Left Achilles Tendon)
  {
    id: "ankle_achilles_left",
    name: k("왼쪽 아킬레스건", "Left Achilles Tendon"),
    koreanName: "왼쪽 아킬레스건",
    englishName: "Left Achilles Tendon",
    category: "joints",
    description: k(
      "왼쪽 발목 뒤쪽 힘줄",
      "Tendon at the back of the left ankle"
    ),
    location: { x: 20, y: 100, region: "left_leg" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 14,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["strike"],
  },
  // 29. 오른쪽 아킬레스건 (Right Achilles Tendon)
  {
    id: "ankle_achilles_right",
    name: k("오른쪽 아킬레스건", "Right Achilles Tendon"),
    koreanName: "오른쪽 아킬레스건",
    englishName: "Right Achilles Tendon",
    category: "joints",
    description: k(
      "오른쪽 발목 뒤쪽 힘줄",
      "Tendon at the back of the right ankle"
    ),
    location: { x: 80, y: 100, region: "right_leg" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 14,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["strike"],
  },
  // 30. 손가락 마디 (Knuckles)
  {
    id: "knuckles_base",
    name: k("손가락 마디", "Knuckles"),
    koreanName: "손가락 마디",
    englishName: "Knuckles",
    category: "joints",
    description: k("손가락의 관절 부분", "Joint area of the fingers"),
    location: { x: 50, y: 98, region: "hands" },
    severity: "minor",
    baseAccuracy: 0.95,
    baseDamage: 8,
    damageMultiplier: 1.1,
    effects: [],
    techniques: ["strike"],
  },
  // 31. 엄지손가락 사이 (Thumb Webbing)
  {
    id: "thumb_webbing",
    name: k("엄지손가락 사이", "Thumb Webbing"),
    koreanName: "엄지손가락 사이",
    englishName: "Thumb Webbing",
    category: "pressure_point",
    description: k(
      "엄지와 검지 사이의 부드러운 부위",
      "Soft area between thumb and index finger"
    ),
    location: { x: 55, y: 97, region: "hands" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 12,
    damageMultiplier: 1.2,
    effects: [],
    techniques: ["pressure_point"],
  },
  // 32. 발등 (Instep)
  {
    id: "instep_top",
    name: k("발등", "Instep"),
    koreanName: "발등",
    englishName: "Instep",
    category: "limbs",
    description: k("발의 윗부분", "Top of the foot"),
    location: { x: 50, y: 105, region: "feet" },
    severity: "minor",
    baseAccuracy: 0.95,
    baseDamage: 8,
    damageMultiplier: 1.1,
    effects: [],
    techniques: ["strike"],
  },
  // 33. 발바닥 앞쪽 (Ball of Foot)
  {
    id: "ball_of_foot",
    name: k("발바닥 앞쪽", "Ball of Foot"),
    koreanName: "발바닥 앞쪽",
    englishName: "Ball of Foot",
    category: "limbs",
    description: k("발바닥의 앞쪽 부분", "Front part of the sole"),
    location: { x: 50, y: 110, region: "feet" },
    severity: "minor",
    baseAccuracy: 0.95,
    baseDamage: 8,
    damageMultiplier: 1.1,
    effects: [],
    techniques: ["strike"],
  },

  // === Additional Vital Points (34–88) ===

  // 34. 어깨 관절 (Shoulder Joint)
  {
    id: "shoulder_joint",
    name: k("어깨 관절", "Shoulder Joint"),
    koreanName: "어깨 관절",
    englishName: "Shoulder Joint",
    category: "joints",
    description: k("어깨의 주요 관절", "Major joint of the shoulder"),
    location: { x: 30, y: 40, region: "arms" },
    severity: "severe",
    baseAccuracy: 0.8,
    baseDamage: 20,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 35. 팔꿈치 관절 (Elbow Joint)
  {
    id: "elbow_joint_general",
    name: k("팔꿈치 관절", "Elbow Joint"),
    koreanName: "팔꿈치 관절",
    englishName: "Elbow Joint",
    category: "joints",
    description: k("팔꿈치의 주요 관절", "Major joint of the elbow"),
    location: { x: 25, y: 60, region: "arms" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 22,
    damageMultiplier: 1.8,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 36. 손목 관절 (Wrist Joint)
  {
    id: "wrist_joint",
    name: k("손목 관절", "Wrist Joint"),
    koreanName: "손목 관절",
    englishName: "Wrist Joint",
    category: "joints",
    description: k("손목의 주요 관절", "Major joint of the wrist"),
    location: { x: 20, y: 90, region: "arms" },
    severity: "severe",
    baseAccuracy: 0.9,
    baseDamage: 18,
    damageMultiplier: 1.6,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 37. 손바닥 중앙 (Palm Center)
  {
    id: "hand_palm_center",
    name: k("손바닥 중앙", "Palm Center"),
    koreanName: "손바닥 중앙",
    englishName: "Palm Center",
    category: "pressure_point",
    description: k(
      "손바닥 중심부의 부드러운 지점",
      "Soft point at the center of the palm"
    ),
    location: { x: 50, y: 92, region: "hands" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 15,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["pressure_point"],
  },
  // 38. 손등 (Back of Hand)
  {
    id: "back_of_hand",
    name: k("손등", "Back of Hand"),
    koreanName: "손등",
    englishName: "Back of Hand",
    category: "limbs",
    description: k("손등의 뼈와 신경", "Bone and nerves at back of hand"),
    location: { x: 50, y: 90, region: "hands" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 14,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["strike"],
  },
  // 39. 중수지절 (Finger PIP Joint)
  {
    id: "finger_pip_joint",
    name: k("중수지절", "Finger PIP Joint"),
    koreanName: "중수지절",
    englishName: "Finger PIP Joint",
    category: "joints",
    description: k(
      "손가락의 근위 지골 관절",
      "Proximal interphalangeal joint of the finger"
    ),
    location: { x: 45, y: 95, region: "hands" },
    severity: "minor",
    baseAccuracy: 0.95,
    baseDamage: 10,
    damageMultiplier: 1.2,
    effects: [],
    techniques: ["strike"],
  },
  // 40. 엄지 관절 (Thumb Joint)
  {
    id: "thumb_joint",
    name: k("엄지 관절", "Thumb Joint"),
    koreanName: "엄지 관절",
    englishName: "Thumb Joint",
    category: "joints",
    description: k("엄지손가락의 관절", "Joint of the thumb"),
    location: { x: 55, y: 96, region: "hands" },
    severity: "minor",
    baseAccuracy: 0.95,
    baseDamage: 10,
    damageMultiplier: 1.2,
    effects: [],
    techniques: ["strike"],
  },
  // 41. 중수골 (Metacarpal Bone)
  {
    id: "metacarpal_bone",
    name: k("중수골", "Metacarpal Bone"),
    koreanName: "중수골",
    englishName: "Metacarpal Bone",
    category: "limbs",
    description: k("손바닥 안쪽 골", "Bone inside the palm"),
    location: { x: 50, y: 90, region: "hands" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 16,
    damageMultiplier: 1.4,
    effects: [],
    techniques: ["strike"],
  },
  // 42. 수근골 (Carpal Bones)
  {
    id: "carpal_bones",
    name: k("수근골", "Carpal Bones"),
    koreanName: "수근골",
    englishName: "Carpal Bones",
    category: "joints",
    description: k("손목의 작은 뼈들", "Small bones of the wrist"),
    location: { x: 20, y: 90, region: "arms" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 18,
    damageMultiplier: 1.5,
    effects: [],
    techniques: ["strike"],
  },
  // 43. 요골 경상돌기 (Radial Styloid Process)
  {
    id: "radial_styloid_process",
    name: k("요골 경상돌기", "Radial Styloid Process"),
    koreanName: "요골 경상돌기",
    englishName: "Radial Styloid Process",
    category: "joints",
    description: k(
      "요골 끝의 돌출된 부분",
      "Prominent part at the end of the radius"
    ),
    location: { x: 20, y: 90, region: "arms" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 15,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["strike"],
  },
  // 44. 척골 경상돌기 (Ulnar Styloid Process)
  {
    id: "ulnar_styloid_process",
    name: k("척골 경상돌기", "Ulnar Styloid Process"),
    koreanName: "척골 경상돌기",
    englishName: "Ulnar Styloid Process",
    category: "joints",
    description: k(
      "척골 끝의 돌출된 부분",
      "Prominent part at the end of the ulna"
    ),
    location: { x: 25, y: 90, region: "arms" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 15,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["strike"],
  },
  // 45. 이두근 건 (Biceps Tendon)
  {
    id: "biceps_tendon",
    name: k("이두근 건", "Biceps Tendon"),
    koreanName: "이두근 건",
    englishName: "Biceps Tendon",
    category: "limbs",
    description: k("상완 근육의 힘줄", "Tendon of the upper arm muscle"),
    location: { x: 30, y: 55, region: "arms" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 20,
    damageMultiplier: 1.6,
    effects: [],
    techniques: ["strike"],
  },
  // 46. 상완 동맥 (Brachial Artery)
  {
    id: "brachial_artery",
    name: k("상완 동맥", "Brachial Artery"),
    koreanName: "상완 동맥",
    englishName: "Brachial Artery",
    category: "vascular",
    description: k("상완의 주요 동맥", "Major artery of the upper arm"),
    location: { x: 30, y: 55, region: "arms" },
    severity: "critical",
    baseAccuracy: 0.75,
    baseDamage: 30,
    damageMultiplier: 2.0,
    effects: [],
    techniques: ["pressure_point"],
  },
  // 47. 주관절와 (Cubital Fossa)
  {
    id: "cubital_fossa",
    name: k("주관절와", "Cubital Fossa"),
    koreanName: "주관절와",
    englishName: "Cubital Fossa",
    category: "pressure_point",
    description: k("팔꿈치 앞쪽 오목한 부위", "Depression at front of elbow"),
    location: { x: 25, y: 60, region: "arms" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 15,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["pressure_point"],
  },
  // 48. 삼각근 부착부 (Deltoid Insertion)
  {
    id: "deltoid_insertion",
    name: k("삼각근 부착부", "Deltoid Insertion"),
    koreanName: "삼각근 부착부",
    englishName: "Deltoid Insertion",
    category: "limbs",
    description: k(
      "어깨 근육이 부착되는 부위",
      "Site where shoulder muscle attaches"
    ),
    location: { x: 30, y: 40, region: "arms" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 16,
    damageMultiplier: 1.4,
    effects: [],
    techniques: ["strike"],
  },
  // 49. 견갑극 (Spine of Scapula)
  {
    id: "scapular_spine",
    name: k("견갑극", "Spine of Scapula"),
    koreanName: "견갑극",
    englishName: "Spine of Scapula",
    category: "limbs",
    description: k("견갑골 뒤쪽 가시 부분", "Spine at back of scapula"),
    location: { x: 35, y: 30, region: "back" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 18,
    damageMultiplier: 1.6,
    effects: [],
    techniques: ["strike"],
  },
  // 50. 겨드랑이 (Axilla)
  {
    id: "axilla",
    name: k("겨드랑이", "Axilla"),
    koreanName: "겨드랑이",
    englishName: "Axilla",
    category: "pressure_point",
    description: k("겨드랑이의 부드러운 부위", "Soft area of the armpit"),
    location: { x: 30, y: 45, region: "arms" },
    severity: "critical",
    baseAccuracy: 0.8,
    baseDamage: 28,
    damageMultiplier: 2.0,
    effects: [],
    techniques: ["pressure_point", "nerve_strike"],
  },
  // 51. 흉골절흔 (Jugular Notch)
  {
    id: "jugular_notch",
    name: k("흉골절흔", "Jugular Notch"),
    koreanName: "흉골절흔",
    englishName: "Jugular Notch",
    category: "neck",
    description: k("흉골 상단의 오목한 부분", "Depression at top of sternum"),
    location: { x: 50, y: 50, region: "neck" },
    severity: "critical",
    baseAccuracy: 0.7,
    baseDamage: 28,
    damageMultiplier: 2.1,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 52. 흉쇄관절 (Sternoclavicular Joint)
  {
    id: "sternoclavicular_joint",
    name: k("흉쇄관절", "Sternoclavicular Joint"),
    koreanName: "흉쇄관절",
    englishName: "Sternoclavicular Joint",
    category: "joints",
    description: k(
      "흉골과 쇄골이 만나는 관절",
      "Joint between sternum and clavicle"
    ),
    location: { x: 45, y: 48, region: "torso" },
    severity: "severe",
    baseAccuracy: 0.8,
    baseDamage: 20,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 53. 쇄골 (Clavicle)
  {
    id: "clavicle",
    name: k("쇄골", "Clavicle"),
    koreanName: "쇄골",
    englishName: "Clavicle",
    category: "torso",
    description: k("상체 앞면의 빗장뼈", "Bone at front of upper body"),
    location: { x: 50, y: 45, region: "torso" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 18,
    damageMultiplier: 1.6,
    effects: [],
    techniques: ["strike"],
  },
  // 54. 늑골연 (Costal Margin)
  {
    id: "costal_margin",
    name: k("늑골연", "Costal Margin"),
    koreanName: "늑골연",
    englishName: "Costal Margin",
    category: "torso",
    description: k("갈비뼈 아래쪽 가장자리", "Lower edge of the ribs"),
    location: { x: 50, y: 60, region: "torso" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 14,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["strike"],
  },
  // 55. 간 부위 (Liver Area)
  {
    id: "liver_area",
    name: k("간 부위", "Liver Area"),
    koreanName: "간 부위",
    englishName: "Liver Area",
    category: "torso",
    description: k(
      "오른쪽 상복부의 간 위치",
      "Location of the liver in the right upper abdomen"
    ),
    location: { x: 60, y: 60, region: "torso" },
    severity: "critical",
    baseAccuracy: 0.8,
    baseDamage: 28,
    damageMultiplier: 2.0,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 56. 비장 부위 (Spleen Area)
  {
    id: "spleen_area",
    name: k("비장 부위", "Spleen Area"),
    koreanName: "비장 부위",
    englishName: "Spleen Area",
    category: "torso",
    description: k(
      "왼쪽 상복부의 비장 위치",
      "Location of the spleen in the left upper abdomen"
    ),
    location: { x: 40, y: 60, region: "torso" },
    severity: "critical",
    baseAccuracy: 0.8,
    baseDamage: 28,
    damageMultiplier: 2.0,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 57. 배꼽 (Umbilicus)
  {
    id: "umbilicus",
    name: k("배꼽", "Navel"),
    koreanName: "배꼽",
    englishName: "Navel",
    category: "pressure_point",
    description: k("복부 중앙의 배꼽 지점", "Navel point at center of abdomen"),
    location: { x: 50, y: 70, region: "torso" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 15,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["pressure_point"],
  },
  // 58. 서혜부 (Groin - Femoral Triangle)
  {
    id: "groin_triangle",
    name: k("서혜부", "Groin (Femoral Triangle)"),
    koreanName: "서혜부",
    englishName: "Groin (Femoral Triangle)",
    category: "vascular",
    description: k(
      "허벅지와 배 사이의 주요 혈관 영역",
      "Area between thigh and abdomen housing major blood vessels"
    ),
    location: { x: 50, y: 85, region: "legs" },
    severity: "critical",
    baseAccuracy: 0.75,
    baseDamage: 30,
    damageMultiplier: 2.2,
    effects: [],
    techniques: ["pressure_point"],
  },
  // 59. 치골결합 (Pubic Symphysis)
  {
    id: "pubic_symphysis",
    name: k("치골결합", "Pubic Symphysis"),
    koreanName: "치골결합",
    englishName: "Pubic Symphysis",
    category: "joints",
    description: k("골반 앞쪽 중앙의 결합 부위", "Pelvic front midline joint"),
    location: { x: 50, y: 90, region: "legs" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 14,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["strike"],
  },
  // 60. 고관절 (Hip Joint)
  {
    id: "hip_joint",
    name: k("고관절", "Hip Joint"),
    koreanName: "고관절",
    englishName: "Hip Joint",
    category: "joints",
    description: k(
      "상체를 하체에 연결하는 큰 관절",
      "Large joint connecting torso to lower body"
    ),
    location: { x: 50, y: 80, region: "legs" },
    severity: "severe",
    baseAccuracy: 0.8,
    baseDamage: 20,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 61. 대전자 (Greater Trochanter)
  {
    id: "greater_trochanter",
    name: k("대전자", "Greater Trochanter"),
    koreanName: "대전자",
    englishName: "Greater Trochanter",
    category: "limbs",
    description: k("대퇴골의 돌출된 부분", "Prominent part of the femur"),
    location: { x: 50, y: 80, region: "legs" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 16,
    damageMultiplier: 1.4,
    effects: [],
    techniques: ["strike"],
  },
  // 62. 대퇴골 체부 (Femur Shaft)
  {
    id: "femur_shaft",
    name: k("대퇴골 체부", "Femur Shaft"),
    koreanName: "대퇴골 체부",
    englishName: "Femur Shaft",
    category: "limbs",
    description: k("허벅지 중심부의 긴 뼈", "Long bone in middle of thigh"),
    location: { x: 50, y: 80, region: "legs" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 20,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["strike"],
  },
  // 63. 슬개골 (Patella)
  {
    id: "patella",
    name: k("슬개골", "Patella"),
    koreanName: "슬개골",
    englishName: "Patella",
    category: "joints",
    description: k("무릎 앞쪽의 쇄골 모양 뼈", "Kneecap bone at front of knee"),
    location: { x: 50, y: 85, region: "legs" },
    severity: "critical",
    baseAccuracy: 0.8,
    baseDamage: 28,
    damageMultiplier: 2.0,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 64. 내측 무릎 관절 (Medial Knee Joint)
  {
    id: "knee_joint_medial",
    name: k("내측 무릎 관절", "Medial Knee Joint"),
    koreanName: "내측 무릎 관절",
    englishName: "Medial Knee Joint",
    category: "joints",
    description: k("무릎 안쪽의 관절 부위", "Joint area on inner side of knee"),
    location: { x: 45, y: 85, region: "legs" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 20,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 65. 외측 무릎 관절 (Lateral Knee Joint)
  {
    id: "knee_joint_lateral",
    name: k("외측 무릎 관절", "Lateral Knee Joint"),
    koreanName: "외측 무릎 관절",
    englishName: "Lateral Knee Joint",
    category: "joints",
    description: k(
      "무릎 바깥쪽의 관절 부위",
      "Joint area on outer side of knee"
    ),
    location: { x: 55, y: 85, region: "legs" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 20,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 66. 슬와 (Popliteal Fossa)
  {
    id: "popliteal_fossa",
    name: k("슬와", "Popliteal Fossa"),
    koreanName: "슬와",
    englishName: "Popliteal Fossa",
    category: "pressure_point",
    description: k("무릎 뒤쪽 오목한 부위", "Depression at back of knee"),
    location: { x: 50, y: 90, region: "legs" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 18,
    damageMultiplier: 1.5,
    effects: [],
    techniques: ["pressure_point"],
  },
  // 67. 경골 결절 (Tibial Tuberosity)
  {
    id: "tibial_tuberosity",
    name: k("경골 결절", "Tibial Tuberosity"),
    koreanName: "경골 결절",
    englishName: "Tibial Tuberosity",
    category: "joints",
    description: k(
      "무릎 바로 아래 경골의 돌출 부위",
      "Prominent area on tibia just below knee"
    ),
    location: { x: 50, y: 90, region: "legs" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 16,
    damageMultiplier: 1.4,
    effects: [],
    techniques: ["strike"],
  },
  // 68. 경골 신경 (Tibial Nerve)
  {
    id: "tibial_nerve",
    name: k("경골 신경", "Tibial Nerve"),
    koreanName: "경골 신경",
    englishName: "Tibial Nerve",
    category: "nerve",
    description: k(
      "종아리 뒤쪽을 따라 내려가는 신경",
      "Nerve running down back of calf"
    ),
    location: { x: 50, y: 95, region: "legs" },
    severity: "severe",
    baseAccuracy: 0.8,
    baseDamage: 22,
    damageMultiplier: 1.6,
    effects: [],
    techniques: ["nerve_strike"],
  },
  // 69. 경골 (Tibia - Shin)
  {
    id: "tibia_shin",
    name: k("경골", "Tibia (Shin)"),
    koreanName: "경골",
    englishName: "Tibia (Shin)",
    category: "limbs",
    description: k("정강이의 주요 뼈", "Major bone of the shin"),
    location: { x: 50, y: 95, region: "legs" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 20,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["strike"],
  },
  // 70. 비골두 (Fibular Head)
  {
    id: "fibula_head",
    name: k("비골두", "Fibular Head"),
    koreanName: "비골두",
    englishName: "Fibular Head",
    category: "limbs",
    description: k("종아리 뼈의 윗부분", "Upper part of the fibula bone"),
    location: { x: 55, y: 95, region: "legs" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 16,
    damageMultiplier: 1.4,
    effects: [],
    techniques: ["strike"],
  },
  // 71. 발목 관절 (Ankle Joint)
  {
    id: "ankle_joint_general",
    name: k("발목 관절", "Ankle Joint"),
    koreanName: "발목 관절",
    englishName: "Ankle Joint",
    category: "joints",
    description: k(
      "발과 다리를 연결하는 관절",
      "Joint connecting foot and leg"
    ),
    location: { x: 50, y: 100, region: "legs" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 20,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 72. 내과 골융기 (Medial Malleolus)
  {
    id: "medial_malleolus",
    name: k("내과 골융기", "Medial Malleolus"),
    koreanName: "내과 골융기",
    englishName: "Medial Malleolus",
    category: "joints",
    description: k("내측 발목의 돌출된 뼈", "Prominent bone on inner ankle"),
    location: { x: 45, y: 100, region: "legs" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 15,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["strike"],
  },
  // 73. 외과 골융기 (Lateral Malleolus)
  {
    id: "lateral_malleolus",
    name: k("외과 골융기", "Lateral Malleolus"),
    koreanName: "외과 골융기",
    englishName: "Lateral Malleolus",
    category: "joints",
    description: k("외측 발목의 돌출된 뼈", "Prominent bone on outer ankle"),
    location: { x: 55, y: 100, region: "legs" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 15,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["strike"],
  },
  // 74. 족저 근막 (Plantar Fascia)
  {
    id: "plantar_fascia",
    name: k("족저 근막", "Plantar Fascia"),
    koreanName: "족저 근막",
    englishName: "Plantar Fascia",
    category: "pressure_point",
    description: k(
      "발바닥의 근막 조직",
      "Connective tissue in the sole of the foot"
    ),
    location: { x: 50, y: 110, region: "feet" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 14,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["pressure_point"],
  },
  // 75. 중족골 (Metatarsal Bones)
  {
    id: "metatarsal_bones",
    name: k("중족골", "Metatarsal Bones"),
    koreanName: "중족골",
    englishName: "Metatarsal Bones",
    category: "joints",
    description: k("발의 중간 부분 뼈들", "Bones in the middle of the foot"),
    location: { x: 50, y: 110, region: "feet" },
    severity: "minor",
    baseAccuracy: 0.95,
    baseDamage: 10,
    damageMultiplier: 1.2,
    effects: [],
    techniques: ["strike"],
  },
  // 76. 발가락 근위 관절 (Toe Proximal Joint)
  {
    id: "toe_proximal_joint",
    name: k("발가락 근위 관절", "Toe Proximal Joint"),
    koreanName: "발가락 근위 관절",
    englishName: "Toe Proximal Joint",
    category: "joints",
    description: k(
      "발가락의 근위 지골 관절",
      "Proximal interphalangeal joint of the toe"
    ),
    location: { x: 50, y: 115, region: "feet" },
    severity: "minor",
    baseAccuracy: 0.95,
    baseDamage: 10,
    damageMultiplier: 1.2,
    effects: [],
    techniques: ["strike"],
  },
  // 77. 무지 지골 관절 (Big Toe IP Joint)
  {
    id: "big_toe_ip_joint",
    name: k("무지 지골 관절", "Big Toe IP Joint"),
    koreanName: "무지 지골 관절",
    englishName: "Big Toe IP Joint",
    category: "joints",
    description: k(
      "엄지발가락의 지골 관절",
      "Interphalangeal joint of the big toe"
    ),
    location: { x: 50, y: 115, region: "feet" },
    severity: "minor",
    baseAccuracy: 0.95,
    baseDamage: 10,
    damageMultiplier: 1.2,
    effects: [],
    techniques: ["strike"],
  },
  // 78. 정중 신경 (Median Nerve - Wrist)
  {
    id: "median_nerve_wrist",
    name: k("정중 신경", "Median Nerve (Wrist)"),
    koreanName: "정중 신경",
    englishName: "Median Nerve (Wrist)",
    category: "nerve",
    description: k(
      "손목을 지나는 주요 신경",
      "Major nerve passing through the wrist"
    ),
    location: { x: 20, y: 90, region: "arms" },
    severity: "severe",
    baseAccuracy: 0.8,
    baseDamage: 20,
    damageMultiplier: 1.6,
    effects: [],
    techniques: ["nerve_strike"],
  },
  // 79. 상안 신경 (Supraorbital Nerve)
  {
    id: "supraorbital_nerve",
    name: k("상안 신경", "Supraorbital Nerve"),
    koreanName: "상안 신경",
    englishName: "Supraorbital Nerve",
    category: "nerve",
    description: k(
      "이마 위쪽을 지나는 신경",
      "Nerve passing above the eyebrow"
    ),
    location: { x: 50, y: 10, region: "head" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 15,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["nerve_strike"],
  },
  // 80. 하안 신경 (Infraorbital Nerve)
  {
    id: "infraorbital_nerve",
    name: k("하안 신경", "Infraorbital Nerve"),
    koreanName: "하안 신경",
    englishName: "Infraorbital Nerve",
    category: "nerve",
    description: k("눈 아래를 지나는 신경", "Nerve passing below the eye"),
    location: { x: 50, y: 25, region: "head" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 15,
    damageMultiplier: 1.3,
    effects: [],
    techniques: ["nerve_strike"],
  },
  // 81. 흉골 자루 (Manubrium - Sternum)
  {
    id: "sternum_manubrium",
    name: k("흉골 자루", "Manubrium (Sternum)"),
    koreanName: "흉골 자루",
    englishName: "Manubrium (Sternum)",
    category: "torso",
    description: k("흉골 상부의 두꺼운 부분", "Upper thick part of sternum"),
    location: { x: 50, y: 52, region: "torso" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 16,
    damageMultiplier: 1.4,
    effects: [],
    techniques: ["strike"],
  },
  // 82. 검상돌기 (Xiphoid Process)
  {
    id: "xiphoid_process",
    name: k("검상돌기", "Xiphoid Process"),
    koreanName: "검상돌기",
    englishName: "Xiphoid Process",
    category: "torso",
    description: k(
      "흉골 아래쪽 돌출된 부분",
      "Prominent lower part of sternum"
    ),
    location: { x: 50, y: 58, region: "torso" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 16,
    damageMultiplier: 1.4,
    effects: [],
    techniques: ["strike"],
  },
  // 83. 횡경막 (Diaphragm)
  {
    id: "diaphragm",
    name: k("횡경막", "Diaphragm"),
    koreanName: "횡경막",
    englishName: "Diaphragm",
    category: "torso",
    description: k(
      "복강과 흉강을 가르는 근육",
      "Muscle separating abdomen and thorax"
    ),
    location: { x: 50, y: 65, region: "torso" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 22,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["strike"],
  },
  // 84. 좌측 신장 (Left Kidney)
  {
    id: "kidney_left",
    name: k("좌측 신장", "Left Kidney"),
    koreanName: "좌측 신장",
    englishName: "Left Kidney",
    category: "torso",
    description: k("왼쪽 등 쪽의 신장", "Left kidney at back"),
    location: { x: 45, y: 75, region: "lower_back" },
    severity: "critical",
    baseAccuracy: 0.8,
    baseDamage: 28,
    damageMultiplier: 2.0,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 85. 우측 신장 (Right Kidney)
  {
    id: "kidney_right",
    name: k("우측 신장", "Right Kidney"),
    koreanName: "우측 신장",
    englishName: "Right Kidney",
    category: "torso",
    description: k("오른쪽 등 쪽의 신장", "Right kidney at back"),
    location: { x: 55, y: 75, region: "lower_back" },
    severity: "critical",
    baseAccuracy: 0.8,
    baseDamage: 28,
    damageMultiplier: 2.0,
    effects: [],
    techniques: ["strike", "pressure_point"],
  },
  // 86. 견갑골 (Scapula)
  {
    id: "scapula",
    name: k("견갑골", "Scapula"),
    koreanName: "견갑골",
    englishName: "Scapula",
    category: "torso",
    description: k("등 상부의 견갑골", "Scapula at upper back"),
    location: { x: 35, y: 30, region: "back" },
    severity: "severe",
    baseAccuracy: 0.85,
    baseDamage: 20,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["strike"],
  },
  // 87. 천추 (Sacral Spine)
  {
    id: "spine_sacral",
    name: k("천추", "Sacral Spine"),
    koreanName: "천추",
    englishName: "Sacral Spine",
    category: "torso",
    description: k("척추의 천골 부분", "Sacral section of the spine"),
    location: { x: 50, y: 85, region: "lower_back" },
    severity: "severe",
    baseAccuracy: 0.8,
    baseDamage: 22,
    damageMultiplier: 1.7,
    effects: [],
    techniques: ["strike"],
  },
  // 88. 미추 (Coccyx)
  {
    id: "spine_coccyx",
    name: k("미추", "Coccyx"),
    koreanName: "미추",
    englishName: "Coccyx",
    category: "torso",
    description: k("척추의 미골 부분", "Coccyx of the spine"),
    location: { x: 50, y: 90, region: "lower_back" },
    severity: "moderate",
    baseAccuracy: 0.9,
    baseDamage: 16,
    damageMultiplier: 1.4,
    effects: [],
    techniques: ["strike"],
  },
];
